### ISSUE TITLE
python3 and emordnilaps string indices must be integers

### ISSUE THREAD

**Issue by Wes4329** [greenglyph/SatorSquare#1]
for py3 compatibility:
$ python sator.py 
  File "sator.py", line 47
    print palindrome, sator_components

line47:
    print (palindrome, sator_components)

for string index must be a number, i'm not sure what needs to happen with this one, perhaps round or truncate the result of divide by 2? I don't understand the logic

line57:
        emordnilaps[len(word)][word[(len(word)/2)]].append(word)

**Comment by greenglyph** [comment]
In line 57 above, we're trying to find the middle character of a string whose length is odd (the 'is_emordnilap' function filters for odd lengths). So if we divide the length by two and truncate, we get the index (starting at 0) of the middle character in the string. We then use that middle character as a key in our dict when storing the word. In the classic sator square example:

>     S A T O R  
>     A R E P O  
>     T E N E T  
>     O P E R A  
>     R O T A S 

we'd be finding the 't' in the middle of 'sator' (which intersects with the 't' in the word 'tenet') and storing 'sator' in the dict with the 'length key' of 5 and the 'middle letter key' of 't'. These keys are used later when iterating over the characters in 'tenet' to find matching intersecting 'emordnilap' words.

I've added the parentheses to the print line as suggested, and am now using int() to truncate the division by 2). 

Thanks for reaching out!
